# Copyright 2026 Adversarial Code Reviewer Contributors
#
# Licensed under the MIT License;
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://opensource.org/licenses/MIT
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for generated code detection."""

import pytest
from pathlib import Path
from unittest.mock import MagicMock

from acr.core.generated_code import GeneratedCodeDetector


class TestGeneratedCodeDetector:
    """Test cases for GeneratedCodeDetector class."""

    def test_init_without_config(self):
        """Test initialization without configuration."""
        detector = GeneratedCodeDetector()
        assert detector.config is None
        assert len(detector._compiled_content_patterns) > 0
        assert len(detector._compiled_file_patterns) > 0
        assert len(detector._compiled_path_patterns) > 0

    def test_init_with_config(self):
        """Test initialization with configuration."""
        mock_config = MagicMock()
        detector = GeneratedCodeDetector(mock_config)
        assert detector.config == mock_config

    def test_detect_from_content_protobuf(self):
        """Test detection of protobuf generated code from content."""
        detector = GeneratedCodeDetector()
        code = """
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""
        file_path = Path("test.py")
        assert detector.detect_from_content(code, file_path) is True

    def test_detect_from_content_grpc(self):
        """Test detection of gRPC generated code from content."""
        detector = GeneratedCodeDetector()
        code = """
# Generated by gRPC Python compiler
# Do not edit
"""
        file_path = Path("test.py")
        assert detector.detect_from_content(code, file_path) is True

    def test_detect_from_content_openapi(self):
        """Test detection of OpenAPI generated code from content."""
        detector = GeneratedCodeDetector()
        code = """
# Generated by OpenAPI Generator
"""
        file_path = Path("test.py")
        assert detector.detect_from_content(code, file_path) is True

    def test_detect_from_content_do_not_edit(self):
        """Test detection of DO NOT EDIT comment."""
        detector = GeneratedCodeDetector()
        code = """
# This code is auto-generated. DO NOT EDIT.
def example():
    pass
"""
        file_path = Path("test.py")
        assert detector.detect_from_content(code, file_path) is True

    def test_detect_from_content_regular_code(self):
        """Test that regular code is not flagged as generated."""
        detector = GeneratedCodeDetector()
        code = """
def example():
    '''Regular function.'''
    return 42
"""
        file_path = Path("test.py")
        assert detector.detect_from_content(code, file_path) is False

    def test_detect_from_filename_pb2(self):
        """Test detection of protobuf _pb2.py files."""
        detector = GeneratedCodeDetector()
        file_path = Path("example_pb2.py")
        assert detector.detect_from_filename(file_path) is True

    def test_detect_from_filename_pb2_grpc(self):
        """Test detection of gRPC _pb2_grpc.py files."""
        detector = GeneratedCodeDetector()
        file_path = Path("example_pb2_grpc.py")
        assert detector.detect_from_filename(file_path) is True

    def test_detect_from_filename_pb(self):
        """Test detection of _pb.py files."""
        detector = GeneratedCodeDetector()
        file_path = Path("example_pb.py")
        assert detector.detect_from_filename(file_path) is True

    def test_detect_from_filename_api(self):
        """Test detection of api_*.py files."""
        detector = GeneratedCodeDetector()
        file_path = Path("api_example.py")
        assert detector.detect_from_filename(file_path) is True

    def test_detect_from_filename_generated(self):
        """Test detection of *_generated.py files."""
        detector = GeneratedCodeDetector()
        file_path = Path("test_generated.py")
        assert detector.detect_from_filename(file_path) is True

    def test_detect_from_filename_regular(self):
        """Test that regular filenames are not flagged."""
        detector = GeneratedCodeDetector()
        file_path = Path("example.py")
        assert detector.detect_from_filename(file_path) is False

    def test_detect_from_path_proto(self):
        """Test detection of proto/ directory."""
        detector = GeneratedCodeDetector()
        file_path = Path("proto/example.py")
        assert detector.detect_from_path(file_path) is True

    def test_detect_from_path_generated(self):
        """Test detection of generated/ directory."""
        detector = GeneratedCodeDetector()
        file_path = Path("generated/test.py")
        assert detector.detect_from_path(file_path) is True

    def test_detect_from_path_openapi(self):
        """Test detection of openapi/ directory."""
        detector = GeneratedCodeDetector()
        file_path = Path("openapi/api.py")
        assert detector.detect_from_path(file_path) is True

    def test_detect_from_path_stubs(self):
        """Test detection of stubs/ directory."""
        detector = GeneratedCodeDetector()
        file_path = Path("stubs/test.py")
        assert detector.detect_from_path(file_path) is True

    def test_detect_from_path_regular(self):
        """Test that regular paths are not flagged."""
        detector = GeneratedCodeDetector()
        file_path = Path("src/example.py")
        assert detector.detect_from_path(file_path) is False

    def test_is_generated_code_content_only(self):
        """Test generated code detection from content only."""
        detector = GeneratedCodeDetector()
        code = "# Generated by Protobuf\n"
        file_path = Path("regular_name.py")
        assert detector.is_generated_code(file_path, code) is True

    def test_is_generated_code_filename_only(self):
        """Test generated code detection from filename only."""
        detector = GeneratedCodeDetector()
        file_path = Path("test_pb2.py")
        assert detector.is_generated_code(file_path) is True

    def test_is_generated_code_path_only(self):
        """Test generated code detection from path only."""
        detector = GeneratedCodeDetector()
        file_path = Path("generated/test.py")
        assert detector.is_generated_code(file_path) is True

    def test_is_generated_code_all_methods(self):
        """Test all detection methods together."""
        detector = GeneratedCodeDetector()
        code = "# Generated\n"
        file_path = Path("generated/test_pb2.py")
        assert detector.is_generated_code(file_path, code) is True

    def test_is_generated_code_false(self):
        """Test that regular code is not flagged as generated."""
        detector = GeneratedCodeDetector()
        code = "def example():\n    return 42\n"
        file_path = Path("src/example.py")
        assert detector.is_generated_code(file_path, code) is False

    def test_is_generated_code_no_source(self):
        """Test detection without source code."""
        detector = GeneratedCodeDetector()
        file_path = Path("test_pb2.py")
        assert detector.is_generated_code(file_path, None) is True

    def test_should_analyze_generated_code_disabled(self):
        """Test that generated code is excluded by default."""
        detector = GeneratedCodeDetector()
        code = "# Generated\n"
        file_path = Path("test_pb2.py")
        assert detector.should_analyze(file_path, code) is False

    def test_should_analyze_regular_code(self):
        """Test that regular code is analyzed."""
        detector = GeneratedCodeDetector()
        code = "def example(): return 42\n"
        file_path = Path("example.py")
        assert detector.should_analyze(file_path, code) is True

    def test_should_analyze_with_config_enabled(self):
        """Test that generated code is analyzed when enabled."""
        mock_config = MagicMock()
        mock_config.analysis.analyze_generated_code = True
        detector = GeneratedCodeDetector(mock_config)
        code = "# Generated\n"
        file_path = Path("test_pb2.py")
        assert detector.should_analyze(file_path, code) is True

    def test_should_analyze_with_config_disabled(self):
        """Test that generated code is excluded when config disables it."""
        mock_config = MagicMock()
        mock_config.analysis.analyze_generated_code = False
        detector = GeneratedCodeDetector(mock_config)
        code = "# Generated\n"
        file_path = Path("test_pb2.py")
        assert detector.should_analyze(file_path, code) is False

    def test_get_excluded_files_empty(self):
        """Test getting excluded files when none are excluded."""
        detector = GeneratedCodeDetector()
        excluded = detector.get_excluded_files()
        assert len(excluded) == 0
        assert isinstance(excluded, set)

    def test_add_excluded_file(self):
        """Test adding an excluded file."""
        detector = GeneratedCodeDetector()
        file_path = Path("test_pb2.py")
        detector.add_excluded_file(file_path)
        excluded = detector.get_excluded_files()
        assert len(excluded) == 1
        assert str(file_path) in excluded

    def test_add_custom_pattern(self):
        """Test adding a custom pattern."""
        detector = GeneratedCodeDetector()
        pattern = r"# Custom generated marker"
        detector.add_custom_pattern(pattern)
        assert pattern in detector._custom_patterns
        assert len(detector._compiled_content_patterns) > len(detector.DEFAULT_PATTERNS)

    def test_add_custom_pattern_invalid(self):
        """Test adding an invalid custom pattern."""
        detector = GeneratedCodeDetector()
        pattern = "[invalid(regex"
        initial_count = len(detector._custom_patterns)
        detector.add_custom_pattern(pattern)
        assert len(detector._custom_patterns) == initial_count

    def test_custom_pattern_detection(self):
        """Test that custom patterns are used for detection."""
        mock_config = MagicMock()
        mock_config.exclude.generated_code_patterns = [r"# CUSTOM GENERATED"]
        detector = GeneratedCodeDetector(mock_config)
        code = "# CUSTOM GENERATED\ndef example(): pass\n"
        file_path = Path("regular.py")
        assert detector.detect_from_content(code, file_path) is True

    def test_get_detection_methods_content(self):
        """Test getting detection methods for content match."""
        detector = GeneratedCodeDetector()
        code = "# Generated\n"
        file_path = Path("regular.py")
        methods = detector.get_detection_methods(file_path, code)
        assert "content" in methods

    def test_get_detection_methods_filename(self):
        """Test getting detection methods for filename match."""
        detector = GeneratedCodeDetector()
        file_path = Path("test_pb2.py")
        methods = detector.get_detection_methods(file_path)
        assert "filename" in methods

    def test_get_detection_methods_path(self):
        """Test getting detection methods for path match."""
        detector = GeneratedCodeDetector()
        file_path = Path("generated/test.py")
        methods = detector.get_detection_methods(file_path)
        assert "path" in methods

    def test_get_detection_methods_multiple(self):
        """Test getting multiple detection methods."""
        detector = GeneratedCodeDetector()
        code = "# Generated\n"
        file_path = Path("generated/test_pb2.py")
        methods = detector.get_detection_methods(file_path, code)
        assert "content" in methods
        assert "filename" in methods
        assert "path" in methods

    def test_get_detection_methods_none(self):
        """Test getting detection methods when none match."""
        detector = GeneratedCodeDetector()
        code = "def example(): pass\n"
        file_path = Path("src/example.py")
        methods = detector.get_detection_methods(file_path, code)
        assert len(methods) == 0

    def test_reset_warnings(self):
        """Test resetting warning tracking."""
        detector = GeneratedCodeDetector()
        code = "# Generated\n"
        file_path = Path("test.py")
        detector.detect_from_content(code, file_path)
        assert len(detector._warned_files) > 0
        detector.reset_warnings()
        assert len(detector._warned_files) == 0

    def test_case_insensitive_detection(self):
        """Test that detection is case-insensitive."""
        detector = GeneratedCodeDetector()
        code = "# generated by protobuf\n"
        file_path = Path("test.py")
        assert detector.detect_from_content(code, file_path) is True

    def test_multiline_detection(self):
        """Test multiline pattern detection."""
        detector = GeneratedCodeDetector()
        code = """
def example():
    pass
# This code is auto-generated
# DO NOT EDIT
"""
        file_path = Path("test.py")
        assert detector.detect_from_content(code, file_path) is True

    def test_node_modules_path(self):
        """Test detection of node_modules/@types/ path."""
        detector = GeneratedCodeDetector()
        file_path = Path("node_modules/@types/example/index.d.ts")
        assert detector.detect_from_path(file_path) is True

    def test_target_generated_sources_path(self):
        """Test detection of Maven target/generated-sources path."""
        detector = GeneratedCodeDetector()
        file_path = Path("target/generated-sources/test.java")
        assert detector.detect_from_path(file_path) is True

    def test_swagger_codegen_content(self):
        """Test Swagger Codegen detection."""
        detector = GeneratedCodeDetector()
        code = """
# Generated by Swagger Codegen
# https://github.com/swagger-api/swagger-codegen
"""
        file_path = Path("test.py")
        assert detector.detect_from_content(code, file_path) is True

    def test_mypy_protobuf_content(self):
        """Test mypy-protobuf detection."""
        detector = GeneratedCodeDetector()
        code = "# Generated by mypy-protobuf. Do not edit!\n"
        file_path = Path("test_pb2.py")
        assert detector.detect_from_content(code, file_path) is True

    def test_generated_decorator(self):
        """Test @generated decorator detection."""
        detector = GeneratedCodeDetector()
        code = """
@generated
class Example:
    pass
"""
        file_path = Path("test.py")
        assert detector.detect_from_content(code, file_path) is True

    def test_codegen_decorator(self):
        """Test @codegen decorator detection."""
        detector = GeneratedCodeDetector()
        code = """
@codegen
def example():
    pass
"""
        file_path = Path("test.py")
        assert detector.detect_from_content(code, file_path) is True

    def test_auto_generated_decorator(self):
        """Test @auto-generated decorator detection."""
        detector = GeneratedCodeDetector()
        code = """
@auto-generated
class Example:
    pass
"""
        file_path = Path("test.py")
        assert detector.detect_from_content(code, file_path) is True

    def test_auto_generated_tag(self):
        """Test <auto-generated> tag detection."""
        detector = GeneratedCodeDetector()
        code = "<auto-generated>\n# Code here\n</auto-generated>\n"
        file_path = Path("test.py")
        assert detector.detect_from_content(code, file_path) is True

    def test_file_path_patterns_pb(self):
        """Test .pb. file pattern detection."""
        detector = GeneratedCodeDetector()
        file_path = Path("example.pb.cc")
        assert detector.detect_from_filename(file_path) is True

    def test_file_path_patterns_grpc(self):
        """Test .grpc. file pattern detection."""
        detector = GeneratedCodeDetector()
        file_path = Path("example.grpc.h")
        assert detector.detect_from_filename(file_path) is True
